name: Bug Report
description: Report a problem or bug in the Kojiro application.
title: "Bug"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this template to help us resolve the issue faster.

  - type: input
    id: description
    attributes:
      label: Bug Description
      placeholder: Describe the bug here
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: Provide the exact steps to reproduce the bug
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Version
      placeholder: 1.0.0
    validations:
      required: true
